apiVersion: v1
kind: ConfigMap
metadata:
  name: db-postgresql
data:
  DB_NAME: mypassword
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==